### ISSUE TITLE
  ImportError: cannot import name 'compare_ssim' from 'skimage.measure'. I need help as I cannot start train.py

### ISSUE THREAD

**Issue by LinuxBeaver** [jiupinjia/SkyAR#22]
Hello, I am having trouble running train.py  

(base) [contrast@cosmos SkyAR-main]$ python train.py \
> --dataset cvprw2020-ade20K-defg \
> --checkpoint_dir checkpoints \
> --vis_dir val_out \
> --in_size 384 \
> --max_num_epochs 200 \
> --lr 1e-4 \
> --batch_size 8 \
> --net_G coord_resnet50
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    import utils
  File "/home/contrast/Desktop/SkyAR-main/utils.py", line 4, in <module>
    from skimage.measure import compare_ssim as sk_cpt_ssim
ImportError: cannot import name 'compare_ssim' from 'skimage.measure' (/home/contrast/Applications/mc/lib/python3.8/site-packages/skimage/measure/__init__.py)
(base) [contrast@cosmos SkyAR-main]$

**Comment by jiupinjia** [comment]
Hi @LinuxBeaver, you can remove line 4 in utils.py and try again. Please let me know whether it works. Thanks!

**Comment by 2zZz2** [comment]
I have the same problem and I fixed it by replacing "from skimage.measure import compare_ssim as sk_cpt_ssim" by "from skimage import measure" and replace "sk_cpt_ssim(_, _)" by "measure.compare_ssim(_, _)" in code.

**Comment by veilm** [comment]
I haven't tried replacing the code but jiupinjia's suggestion of removing line 4 worked for me
